## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
branches:
  only:
    - master
notifications:
  email: false
git:
  depth: 99999999
after_success:
  # build docs
  - julia -e 'cd(Pkg.dir("Examples")); Pkg.add("Documenter"); include("docs/make.jl")'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Examples")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Examples")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
